### ISSUE TITLE
Accept sub-path in listener rules

### ISSUE THREAD

**Issue by wichert** [awslabs/ecs-refarch-cloudformation#13]
I spent way too much time debugging something that ended up being completely trivial: I had missed the fact that the example service only listen for an exact path:

```yaml
    ListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref Listener
            Priority: 2
            Conditions:
                - Field: path-pattern
                  Values: 
                    - !Ref Path
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward
```

My services, and most I suspect unless your micro services are _really_ tiny, handle a fair number of subpaths as well, so I needed two listeners rules:

```yaml
    RootListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref Listener
            Priority: 100
            Conditions:
                - Field: path-pattern
                  Values:
                    - !Ref Path
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward

    SubListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref Listener
            Priority: 101
            Conditions:
                - Field: path-pattern
                  Values:
                    - !Sub ${Path}/*
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward
```

Would it make sense to do that in the reference templates as well? If so I'll happily submit a PR.
