### ISSUE TITLE
Specify a Bucket Name

### ISSUE THREAD

**Issue by piedmont01** [awslabs/ecs-refarch-cloudformation#29]
Add the following parameter in the master.yaml. 

```
Parameters:
  BucketName:
    Type: String
    Description: Name of bucket containing YAML scripts needed to build cluster
```

And replace the TemplateURL

```
TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/infrastructure/vpc.yaml
```
