### ISSUE TITLE
Implicit casting of string to List?

### ISSUE THREAD

**Issue by rbirkby** [awslabs/ecs-refarch-cloudformation#3]
The master template pulls a string output from vpc.yaml into ec-cluster.yaml as a List. Is this possible? Does CloudFormation support implicit casting?

vpc.yaml outputs a string: 

``` yaml
    PrivateSubnets:
        Description: A list of the private subnets
        Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]]
```

The [docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html) for Join say:

```
Returns 
The combined string.
```

ecs-cluster.yaml accepts a list, not a string:

``` yaml
    Subnets:
        Description: Choose which subnets this ECS cluster should be deployed to
        Type: List<AWS::EC2::Subnet::Id>
```

master.yaml sends the string to  ec-cluster.yaml:

```
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
```

How is this possible? CloudFormation AFAIK does not support casting of data types.
