### ISSUE TITLE
DefaultPublicRoute missing DependsOn?

### ISSUE THREAD

**Issue by AdrienFromToulouse** [awslabs/ecs-refarch-cloudformation#6]
Hi!

Thanks for the example, it is very helpful to me!

Should not a `DependsOn` on the `InternetGatewayAttachment` be added to the `DefaultPublicRoute` resource?

Indeed it looks like working better when present. in order to prevent having that type of error:

`route table rtb-xxxxxxx and network gateway igw-xxxxx belong to different networks.`

```yaml
DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
```

Cheers!
